name = "duosync"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

# D1 binding available to Pages Functions as `env.DB`.
[[d1_databases]]
binding = "DB"
database_name = "duosync"
database_id = "d041d28b-5c00-4677-bf29-951a059a9f57"
migrations_dir = "db/migrations"
